CC=gcc
SRC=*.c
EXE=Bank_Management_System
build:
	$(CC) -g $(SRC) -o $(EXE)
run:
	./$(EXE)
clean:
	rm -f *.o *.s *.i $(EXE)
lint:
	splint $(SRC)
check:
	valgrind --leak-check=yes ./$(EXE)
execute: clean build run
memcheck: clean build check